#ifndef PENETRATIONCOUNT_GLOBAL_H
#define PENETRATIONCOUNT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PENETRATIONCOUNT_LIB
# define PENETRATIONCOUNT_EXPORT Q_DECL_EXPORT
#else
# define PENETRATIONCOUNT_EXPORT Q_DECL_IMPORT
#endif

#endif // PENETRATIONCOUNT_GLOBAL_H
